version: '3'

services:
  docs:
    image: my_blog_saas_local_docs
    container_name: my_blog_saas_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./my_blog_saas:/app/my_blog_saas:z
    ports:
      - '9000:9000'
    command: /start-docs
